### ISSUE TITLE
AR05 - chyba vo vzorci

### ISSUE THREAD

**Issue by xirha** [PracovnyBod/ADRIA#1]
AR05 - MRAC Gradientny
V rovnici (48b) chyba vo vyraze v zatvorke `theta 2`, ktora vyplyva z predchadzajucej rovnice. Potom bude vyraz v zatvorke davat zmysel a bude sa dat nahradit `y` a vyjadrit rovnica (48c)

**Comment by PracovnyBod** [comment]
Chyba opravená.
Vďaka!
